### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dmamontov** [iamalnewkirk/faker#13]
Will there be support for other localizations?

**Comment by iamalnewkirk** [comment]
The short answer is "yes" but only if someone else wants to contribute such plugins to the core, otherwise "no". The library has been refactored such that all generators are simple plugins, most of which use methods provided by `Faker::Process`. If you want to contribute non-English plugins I'd be happy to help get you started!

**Comment by iamalnewkirk** [comment]
See this more an intro! https://metacpan.org/pod/release/AWNCORP/Faker-1.01/lib/Faker.pm#autoloading-under
